# version: '3'
# services:
#   website:
#     build: .
#     networks:
#       - nginx_network
#       - rabbitmq_network
#       - postgres_network
#     depends_on:
#       - database
#   nginx:
#     image: nginx:1.13-alpine
#     volumes:
#       - ./configs/nginx/docker_mdblog.conf:/etc/nginx/conf.d/default.conf:ro
#     ports:
#       - 80:80
#     depends_on:
#       - website
#     networks:
#       - nginx_network
#   rabbitmq:
#     image: rabbitmq:3.7-alpine
#     networks:
#       - rabbitmq_network
#   celery:
#     build: .
#     command: celery worker -l info -A mdblog.cli:celery_app
#     depends_on:
#       - rabbitmq
#       - database
#     networks:
#       - rabbitmq_network
#       - postgres_network
#   database:
#     image: postgres:10.3-alpine
#     environment:
#       - POSTGRES_USER=docker
#       - POSTGRES_PASSWORD=docker
#     volumes:
#       - dbdata:/var/lib/postgresql/data
#     networks:
#       - postgres_network

# networks:
#   nginx_network:
#     driver: bridge

#   postgres_network:
#     driver: bridge

#   rabbitmq_network:
#     driver: bridge

# volumes:
#   dbdata:


version: '3'
services:
    website:
        build: .
        networks:
            - nginx_network
            - rabbitmq_network
            - postgres_network
        depends_on:
            - database

    nginx:
        image: nginx:1.13-alpine
        volumes:
            - ./configs/nginx/docker_mdblog.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - website
        networks:
            - nginx_network

    rabbitmq:
        image: rabbitmq:3.7-alpine
        networks:
            - rabbitmq_network

    celery:
        build: .
        command: celery worker -l info -A mdblog.cli:celery_app
        depends_on:
            - rabbitmq
            - database
        networks:
            - rabbitmq_network
            - postgres_network

    database:
        image: postgres:10.3-alpine
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - postgres_network

networks:
    nginx_network:
        driver: bridge

    rabbitmq_network:
        driver: bridge

    postgres_network:
        driver: bridge

volumes:
    dbdata: