import os

SECRET_KEY = b'F\x9c\x83.\xca\x0e\xa3\xa9\x8b=\xeaDo\xc1\x99\xddp]@\xaa\xcfOG\x0f'
DEBUG = False
SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL")
SQLALCHEMY_TRACK_MODIFICATIONS = False

EMAIL_USERNAME = os.environ.get("MDBLOG_EMAIL_USERNAME", None)
EMAIL_PASSWORD = os.environ.get("MDBLOG_EMAIL_PASSWORD", None)

CELERY_BROKER_URL="pyamqp://guest@localhost//"

BROKER_URL = os.environ.get("CLOUDAMQP_URL")

BROKER_POOL_LIMIT = 1
BROKER_HEARTBEAT = None
BROKER_CONNECTION_TIMEOUT = 30
CELERY_RESULT_BACKEND = None
EVENT_QUEUE_EXPIRES = 60
WORKER_PREFETCH_MULTIPLIER = 1
WORKER_CONCURRENCY = 50